Ankn-Morpork-MVC/Controllers/BeerController.cs
using Ankn_Morpork_MVC.Models;
using Ankn_Morpork_MVC.NPCsRepository;
using System.Linq;
using System.Web.Mvc;

namespace Ankn_Morpork_MVC.Controllers
{
    public class BeerController : Controller
    {
        private ApplicationDbContext _context;

        public BeerController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult MendedDrumPub()
        {
            return View();
        }

        public ActionResult ReturnBeerResult(Player player)
        {
            if (!ModelState.IsValid)
                return View("MendedDrumPub");

            var realPlayer = _context.Player.FirstOrDefault();

            realPlayer.BeerAmount += player.BeerAmount;
            realPlayer.MoneyQuantity -= PlayerRepository.CalculateBeerCost(player.BeerAmount);
            realPlayer.IsInPub = false;

            _context.SaveChanges();

            return RedirectToAction("Index", "Game");
        }
    }
}

Ankn-Morpork-MVC/Views/Beer/MendedDrumPub.cshtml
@model Ankn_Morpork_MVC.Models.Player

@{
    ViewBag.Title = "Mended Drum Pub";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mended Drum Pub</h2>

<h5>Enter how many pints of beer you want to buy(max = 2)</h5>

@using (Html.BeginForm("ReturnBeerResult", "Beer"))
{
    @Html.TextBoxFor(m => m.BeerAmount, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.BeerAmount);
    <br />
    <button type="submit" class="btn btn-primary">Confirm</button>
}