Ankn-Morpork-MVC/Models/Assasin.cs
using Ankn_Morpork_MVC.Models.ModelInterfaces;
using System.ComponentModel.DataAnnotations;

namespace Ankn_Morpork_MVC.Models
{
    public class Assasin : IGuildNPC
    {
        public int Id { get; set; }

        public int MinReward { get; set; }

        public int MaxReward { get; set; }

        public bool IsBusy { get; set; } 

        [Required(ErrorMessage = "Please enter numbers")]
        [Display(Name = "Reward")]
        public decimal PlayerRewardForNPC { get; set; }
    }
}

Ankn-Morpork-MVC/Controllers/AssasinController.cs
using Ankn_Morpork_MVC.Models;
using Ankn_Morpork_MVC.NPCsBuilder;
using Ankn_Morpork_MVC.NPCsRepository;
using System.Linq;
using System.Web.Mvc;

namespace Ankn_Morpork_MVC.Controllers
{
    public class AssasinController : Controller
    {
        private ApplicationDbContext _context;
        private NPCRepository _npcRepository;
        private Player _player;
        private PlayerBuilder _builder;

        public AssasinController()
        {
            _context = new ApplicationDbContext();
            _npcRepository = new NPCRepository(_context);
            _builder = new PlayerBuilder();
        }

        public ActionResult GetAssasinReward()
        {
            return View();
        }

        public ActionResult ReturnReward(Assasin assasin)
        {
            if(!ModelState.IsValid)
                return View("GetAssasinReward");

            _player = _builder.ReturnPlayer();
            _player.CurrentNpcTypeForPlay = _context.CurrentNpcs.FirstOrDefault();
            _npcRepository.GetNPCById(_player);

            _player.CurrentNpcForPlay.PlayerRewardForNPC = assasin.PlayerRewardForNPC;

            _context.SaveChanges();

            return RedirectToAction("Continue", "Game");
        }
    }
}

Ankn-Morpork-MVC/Views/Assasin/GetAssasinReward.cshtml
@model Ankn_Morpork_MVC.Models.Assasin

@{
    ViewBag.Title = "GetAssasinReward";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Enter your reward for Assasin Guild</h2>

@using (Html.BeginForm("ReturnReward", "Assasin"))
{
    @Html.TextBoxFor(m => m.PlayerRewardForNPC, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.PlayerRewardForNPC);
    <br />
    <button type="submit" class="btn btn-primary">Confirm</button>
 }